import fs from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import { downloadMediaMessage } from '@itsliaaa/baileys'
import { evoGet, requireEvoGbApiKey } from '../lib/api.js'

const q = ctx => ctx.args.join(' ').trim()
function quoted(msg){const c=msg.message?.extendedTextMessage?.contextInfo||msg.message?.audioMessage?.contextInfo||msg.message?.videoMessage?.contextInfo;return c?.quotedMessage?{key:{remoteJid:msg.key.remoteJid,id:c.stanzaId,participant:c.participant},message:c.quotedMessage}:msg}
async function media(ctx){try{return await downloadMediaMessage(quoted(ctx.msg),'buffer',{}, {logger:console,reuploadRequest:ctx.sock.updateMediaMessage})}catch{return null}}
async function multipart(endpoint,b,filename='archivo.bin',params={}){const key=requireEvoGbApiKey();const url=new URL(endpoint,process.env.EVOGB_API_BASE_URL||'https://api.evogb.org');url.searchParams.set('key',key);for(const[k,v]of Object.entries(params))if(v!==undefined&&v!=='')url.searchParams.set(k,String(v));const f=new FormData();f.append('file',new Blob([b]),filename);const r=await fetch(url,{method:'POST',body:f});const d=await r.json().catch(()=>({}));if(!r.ok||d.status===false)throw new Error(d.message||`HTTP ${r.status}`);return d}

export const shortlink={name:'acortar',aliases:['shortlink'],async execute(ctx){const [url,alias]=ctx.args;if(!url)throw new Error('Uso: .acortar <url> [alias]');const d=await evoGet('/tools/shortlink',{url,alias});await ctx.sock.sendMessage(ctx.chat,{text:`🔗 *Enlace acortado*\n\nOriginal: ${d.original||url}\nCorto: ${d.shorturl}\nDuración: ${d.duration||'permanent'}`},{quoted:ctx.msg})}}
export const hostinfo={name:'hostinfo',aliases:[],async execute(ctx){const domain=q(ctx);if(!domain)throw new Error('Uso: .hostinfo <dominio o URL>');const d=await evoGet('/tools/hostinfo',{domain});const x=d.info?.[0]||{};await ctx.sock.sendMessage(ctx.chat,{text:`🌐 *Información del host*\nIP: ${x.ip||'?'}\nNombre: ${x.name||'?'}\nOrganización: ${x.organisation||'?'}\nRegión: ${x.region||'?'}\nCiudad: ${x.city||'?'}\nZona horaria: ${x.tzone||'?'}`},{quoted:ctx.msg})}}
export const minecraft={name:'minecraft',aliases:['mcstatus'],async execute(ctx){const host=ctx.args[0],edition=ctx.args[1]||'all';if(!host)throw new Error('Uso: .minecraft <host> [java|bedrock|all]');const d=await evoGet('/tools/minecraft',{host,edition});const lines=[`⛏️ *Minecraft Server*`,`Host: ${d.host||host}`,`IP: ${(d.dns_ips||[]).join(', ')||'?'}`];for(const k of ['java','bedrock']){const x=d[k];if(!x)continue;lines.push('',`*${k.toUpperCase()}*`,`Estado: ${x.status||'?'}`,`Puerto: ${x.port||'?'}`,`Versión: ${String(x.version?.name_clean||x.version?.name||'?').replace(/§./g,'')}`,`Jugadores: ${x.players?.online??'?'} / ${x.players?.max??'?'}`,`MOTD: ${String(x.motd?.clean||'').replace(/§./g,'').trim()||'?'}`)}await ctx.sock.sendMessage(ctx.chat,{text:lines.join('\n')},{quoted:ctx.msg})}}
export const npm={name:'npm',aliases:['npmjs'],async execute(ctx){const query=q(ctx);if(!query)throw new Error('Uso: .npm <paquete>');const d=await evoGet('/tools/npmjs',{query,mode:'summary'});const x=d.result||{};await ctx.sock.sendMessage(ctx.chat,{text:`📦 *${x.name||query}*\nVersión: ${x.version||'?'}\nDescripción: ${x.description||'?'}\nLicencia: ${x.license||'?'}\nAutor: ${x.author||'?'}\nDescargas/mes: ${Number(x.downloads_last_month||0).toLocaleString('es-PE')}\nRepositorio: ${x.homepage||x.repository||'?'}`},{quoted:ctx.msg})}}
export const npmfull={name:'npmfull',aliases:['npmraw'],async execute(ctx){const query=q(ctx);if(!query)throw new Error('Uso: .npmfull <paquete>');const d=await evoGet('/tools/npmjs',{query,mode:'all'});const file=path.join(os.tmpdir(),`${query.replace(/[^a-z0-9_-]/gi,'_')}-npm.json`);await fs.writeFile(file,JSON.stringify(d.result||d,null,2));try{await ctx.sock.sendMessage(ctx.chat,{document:await fs.readFile(file),mimetype:'application/json',fileName:path.basename(file),caption:`📦 Respuesta completa de NPM: ${query}`},{quoted:ctx.msg})}finally{fs.unlink(file).catch(()=>{})}}}
export const shazam={name:'shazam',aliases:['whatmusic'],async execute(ctx){const b=await media(ctx);if(!b)throw new Error('Responde a un audio o video con .shazam');const d=await multipart('/tools/whatmusic-shazam',b,'media.mp4',{method:'local'});const x=d.data||{},i=x.info||{},c=x.detection?.confidence||{};const caption=`🎵 *${i.title||'Canción identificada'}*\nArtista: ${i.artist||'?'}\nÁlbum: ${i.album||'?'}\nAño: ${i.year||'?'}\nGénero: ${i.genre||'?'}\nCoincidencia: ${c.percentage??'?'}%`;if(x.media?.cover)await ctx.sock.sendMessage(ctx.chat,{image:{url:x.media.cover},caption},{quoted:ctx.msg});else await ctx.sock.sendMessage(ctx.chat,{text:caption},{quoted:ctx.msg})}}

export const extraUtilityCommands=[shortlink,hostinfo,minecraft,npm,npmfull,shazam]
