import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import config from '../../config.js'
import { formatDateTime, jidToNumber } from '../lib/format.js'
const __dirname=path.dirname(fileURLToPath(import.meta.url));const projectRoot=path.resolve(__dirname,'../..')
const deco='ㅤۚ𑁯ׂᰍ  ☕ ᳴   ׅ  ׄʚ   ̶ '
const item=(cmd,desc)=>`${deco}*${cmd}*\n> ✦ ${desc}`
const entries=[
 ['.tiktok • .tt + [url]','Descarga videos de TikTok.'],['.ttimg • .ttmp3 + [url]','Descargar fotos/audio de un post de TikTok.'],['.tts • .tiktoks + [búsqueda]','Buscar videos de TikTok en una lista seleccionable.'],['.mediafire • .mf + [url]','Descargar un archivo de MediaFire.'],['.mega • .meganz + [url]','Descargar un archivo de Mega.nz.'],['.terabox • .tera + [url]','Descargar un archivo de Terabox.'],['.ytmp3 • .play + [nombre o url]','Descargar audio de YouTube.'],['.ytmp4 • .play2 + [nombre o url]','Descargar video de YouTube.'],['.yts • .ytsdl + [búsqueda]','Busca en YouTube y elige audio/video.'],['.spotify • .ytmusic + [búsqueda]','Busca y descarga música.'],['.fb • .facebook + [url]','Descargar videos de Facebook.'],['.twitter • .x + [url]','Descargar contenido de Twitter/X.'],['.hitube • .multidl + [url]','Descarga multi-red.'],['.ig • .instagram + [url]','Descargar contenido de Instagram.'],['.apk • .modapk + [nombre]','Descargar APKs.'],['.gitclone + [url]','Descargar repositorios de GitHub.'],['.npmdl + [paquete]','Descargar paquetes desde NPM.'],['.animelinks • .animedl + [nombre] [ep]','Ver enlaces de anime.'],['.pinterest • .pin + [búsqueda o url]','Buscar o descargar imágenes de Pinterest.'],['.sticker • .s','Crear sticker.'],['.stickersearch','Buscar y descargar paquetes de stickers.'],['.ia • .gemini • .claude • .qwen','Comandos de inteligencia artificial.'],['.editimg • .imgprompt','Editar imágenes y generar prompts.'],['.antinsfw • .antilink','Seguridad y moderación.'],['.bienvenida • .despedida','Configurar entradas y salidas.'],['.promote • .demote • .kick','Administrar participantes.'],['.code','Crear un subbot con código de vinculación NERO.'],['.bots','Ver subbots, uptime y dispositivo.'],['.setprincipal • .setbot','Elegir el bot principal de este grupo.'],['.principal • .resetprincipal','Consultar o restablecer la instancia principal.'],['.logout','Eliminar tu sesión de subbot del VPS.'],['.reportar + [motivo]','Reportar errores al Owner y SubOwner.'],['.modo','Elegir si esta instancia responde también en privado.'],['.vv • .ownerinfo • .restart','Herramientas del Owner.']
]
export const command={name:'menu',aliases:['help','comandos'],description:'Muestra todos los comandos.',async execute({sock,msg,chat,sender,instanceType}){const {date,time}=formatDateTime(config.timezone);const mention=`@${jidToNumber(sender)}`;const body=[`╭───── *${config.botName}* ─────╮`,`> Usuario: ${mention}`,`> Creador: ${config.creator}`,`> Versión: ${config.version}`,`> Instancia: ${instanceType==='subbot'||config.instanceType==='subbot'?'Subbot':'Bot principal'}`,`> Fecha: ${date}`,`> Hora: ${time}`,`> Web: ${config.website}`,'╰────────────────╯','',...entries.map(([c,d])=>item(c,d)),'╰──── ੈ₊˚༅༴╰────︶.︶ ⸙ ͛ ͎ ͛ ︶.︶ ੈ₊˚༅'].join('\n\n');try{const video=await fs.readFile(path.resolve(projectRoot,config.menuVideo));await sock.sendMessage(chat,{video,gifPlayback:true,caption:body,mentions:[sender]},{quoted:msg})}catch{await sock.sendMessage(chat,{text:body,mentions:[sender]},{quoted:msg})}}}
