import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import config from '../../config.js'
import { formatDateTime, jidToNumber } from '../lib/format.js'
const __dirname=path.dirname(fileURLToPath(import.meta.url));const projectRoot=path.resolve(__dirname,'../..')
const item=(c,d)=>[`│ ✦ *${c}*`,`> ✐ ${d}`]
const section=(t,e)=>[`╭─❧ *${t}*`,...e.flatMap(x=>item(...x)),'╰────────────❧'].join('\n')
const entries={
 descargas:[['.play / .ytmp3 / .ytmp4','Busca y descarga audio o video de YouTube.'],['.spotify / .ytmusic','Busca y descarga música.'],['.tiktok / .instagram / .facebook','Descarga contenido mediante enlace.'],['.tiktoksearch','Prueba el carrusel directo y muestra una lista compatible.'],['.mediafire / .mega / .terabox','Descarga archivos.'],['.apk / .apkmod','Busca y descarga APK.']],
 buscadores:[['.googleimages','Busca imágenes en Google.'],['.pinterestsearch','Busca imágenes en Pinterest.'],['.wikipedia','Consulta Wikipedia.'],['.stickersearch','Busca paquetes de Sticker.ly.']],
 herramientas:[['.hd / .upscale / .restaurar','Mejora o restaura imágenes.'],['.convertir / .comprimir / .removebg','Convierte, comprime o elimina fondos.'],['.qr / .ytthumb / .ssweb','Genera QR, miniaturas o capturas web.'],['.traducir / .ocr / .transcribir','Traduce, lee imágenes o transcribe audios.'],['.shazam / .quitarvoz','Reconoce música o separa sus pistas.']],
 stickers:[['.sticker / .s','Crea un sticker respondiendo a una imagen.'],['.stickerwm paquete|autor','Crea un sticker con metadatos personalizados.'],['.renombrarsticker paquete|autor','Cambia nombre y autor del paquete.'],['.toimg','Convierte un sticker estático en imagen.'],['.textosticker','Crea un sticker de texto.']],
 ia:[['.ia <pregunta>','Conversa con la IA personalizada de Nero Bot.'],['.gemini <pregunta>','Consulta Gemini con personalidad ArcadiaCorps.'],['.claude <pregunta>','Obtén ayuda extensa y de programación.'],['.qwen <pregunta>','Consulta Qwen.'],['.bot <instrucción>','Analiza, resume, corrige o traduce un mensaje citado.'],['.imgprompt','Convierte una imagen citada en prompt.'],['.editimg <instrucción>','Edita una imagen con NanoBanana.']],
 anime:[['.animenews','Muestra noticias recientes de MyAnimeList.'],['.animeschedule','Muestra emisiones y próximos episodios.'],['.neko','Envía una imagen neko aleatoria.'],['.bluearchive','Envía una imagen de Blue Archive.'],['.angry','Envía una reacción anime de enojo.']],
 administracion:[['.antinsfw on/off','Modera contenido +18 con EvoGB; 3 advertencias expulsan.'],['.antilink on/off','Elimina enlaces no permitidos.'],['.warn / .warns / .resetwarn','Administra advertencias.'],['.bienvenida / .despedida on/off','Activa mensajes de entrada y salida.'],['.setbienvenida / .setdespedida','Personaliza los textos.'],['.setimgbienvenida / .setimgdespedida','Guarda imágenes personalizadas.'],['.setname / .setdesc','Cambia nombre o descripción del grupo.'],['.abrir / .cerrar','Abre o cierra el grupo.'],['.abrirgrupo 30m / .cerrargrupo 30m','Programa apertura o cierre automático.'],['.promote / .demote / .kick','Gestiona participantes.'],['.tagall / .hidetag','Menciona a todos.'],['.groupconfig','Muestra la configuración del grupo.']],
 owner:[['.vv','Recupera manualmente una foto o video de una sola vista.'],['.testcards','Prueba el carrusel directo del fork.']]
}
const menus=Object.fromEntries(Object.entries(entries).map(([k,v])=>[k,()=>section(k.toUpperCase(),v)]))
export const command={name:'menu',aliases:['help','comandos',...Object.keys(entries)],description:'Muestra los comandos.',async execute({sock,msg,chat,sender,text}){const invoked=text.slice(config.prefix.length).trim().split(/\s+/)[0].toLowerCase();if(menus[invoked])return sock.sendMessage(chat,{text:menus[invoked]()},{quoted:msg});const {date,time}=formatDateTime(config.timezone);const mention=`@${jidToNumber(sender)}`;const body=[`╭─❧ *${config.botName}*`,`│ ✐ *Usuario ›* ${mention}`,`│ ✐ *Creador ›* ${config.creator}`,`│ ✐ *Plugins ›* ${config.plugins}`,`│ ✐ *Versión ›* ${config.version}`,`│ ✐ *Link ›* ${config.website}`,`│ ✐ *Fecha ›* ${date}`,`│ ✐ *Hora ›* ${time}`,'╰────────────❧','',...Object.entries(entries).flatMap(([k,v])=>[section(k.toUpperCase(),v),''])].join('\n');try{const video=await fs.readFile(path.resolve(projectRoot,config.menuVideo));await sock.sendMessage(chat,{video,gifPlayback:true,caption:body,mentions:[sender]},{quoted:msg})}catch{await sock.sendMessage(chat,{text:body,mentions:[sender]},{quoted:msg})}}}
