import { jidNormalizedUser, downloadMediaMessage } from '@itsliaaa/baileys'
import fs from 'node:fs/promises'
import path from 'node:path'
import { getGroup, patchGroup, getWarn, setWarn, resetWarn, saveTimer, clearTimer } from '../lib/groupStore.js'

function targetFromMsg(ctx){const m=ctx.msg.message||{};const c=m.extendedTextMessage?.contextInfo||m.imageMessage?.contextInfo||m.videoMessage?.contextInfo;return jidNormalizedUser(c?.mentionedJid?.[0]||c?.participant||'')}
async function metadata(ctx){if(!ctx.chat.endsWith('@g.us'))throw new Error('Este comando solo funciona en grupos.');return ctx.sock.groupMetadata(ctx.chat)}
async function requireAdmin(ctx){const m=await metadata(ctx);const p=m.participants.find(x=>jidNormalizedUser(x.id)===ctx.sender);if(!p?.admin&&!ctx.isOwner&&!ctx.isSubOwner)throw new Error('Solo administradores pueden usar este comando.');return m}
async function requireBotAdmin(ctx){const m=await requireAdmin(ctx);const bot=m.participants.find(x=>jidNormalizedUser(x.id)===jidNormalizedUser(ctx.sock.user?.id||''));if(!bot?.admin)throw new Error('El bot necesita ser administrador.');return m}
const wrap=(name,aliases,fn)=>({name,aliases,async execute(ctx){try{await fn(ctx)}catch(e){await ctx.sock.sendMessage(ctx.chat,{text:`❌ ${e.message}`},{quoted:ctx.msg})}}})
function toggle(ctx,key,label){return requireAdmin(ctx).then(()=>{const value=(ctx.args[0]||'').toLowerCase();if(!['on','off'].includes(value))throw new Error(`Uso: .${ctx.text.includes(' ')?ctx.text.split(' ')[0].slice(1):key} on/off`);patchGroup(ctx.chat,{[key]:value==='on'});return ctx.sock.sendMessage(ctx.chat,{text:`✅ ${label} ${value==='on'?'activado':'desactivado'}.`},{quoted:ctx.msg})})}
function durationMs(value=''){const m=value.toLowerCase().match(/^(\d+)(s|m|h|d)$/);if(!m)return 0;const n=Number(m[1]);return n*({s:1000,m:60000,h:3600000,d:86400000}[m[2]])}
async function scheduleGroup(ctx,type){await requireBotAdmin(ctx);const ms=durationMs(ctx.args[0]);if(!ms)throw new Error(`Uso: .${type==='announcement'?'cerrargrupo':'abrirgrupo'} 30m`);const when=Date.now()+ms;saveTimer(ctx.chat,type,when);setTimeout(async()=>{await ctx.sock.groupSettingUpdate(ctx.chat,type).catch(()=>{});clearTimer(ctx.chat,type)},ms);await ctx.sock.sendMessage(ctx.chat,{text:`⏰ Grupo programado para ${type==='announcement'?'cerrarse':'abrirse'} en ${ctx.args[0]}.`},{quoted:ctx.msg})}
export const antinsfw=wrap('antinsfw',['nsfw'],ctx=>toggle(ctx,'antiNsfw','Anti-NSFW de EvoGB'))
export const antilink=wrap('antilink',[],ctx=>toggle(ctx,'antiLink','Anti-enlaces'))
export const welcome=wrap('bienvenida',['welcome'],ctx=>toggle(ctx,'welcome','Bienvenida'))
export const goodbye=wrap('despedida',['goodbye'],ctx=>toggle(ctx,'goodbye','Despedida'))
export const setwelcome=wrap('setbienvenida',[],async ctx=>{await requireAdmin(ctx);const text=ctx.args.join(' ').trim();if(!text)throw new Error('Uso: .setbienvenida <texto>');patchGroup(ctx.chat,{welcomeText:text});await ctx.sock.sendMessage(ctx.chat,{text:'✅ Mensaje de bienvenida actualizado.'},{quoted:ctx.msg})})
export const setgoodbye=wrap('setdespedida',[],async ctx=>{await requireAdmin(ctx);const text=ctx.args.join(' ').trim();if(!text)throw new Error('Uso: .setdespedida <texto>');patchGroup(ctx.chat,{goodbyeText:text});await ctx.sock.sendMessage(ctx.chat,{text:'✅ Mensaje de despedida actualizado.'},{quoted:ctx.msg})})
async function saveGroupImage(ctx,key){await requireAdmin(ctx);const m=ctx.msg.message||{};const c=m.extendedTextMessage?.contextInfo||m.imageMessage?.contextInfo;const target=c?.quotedMessage?{key:{remoteJid:ctx.msg.key.remoteJid,id:c.stanzaId,participant:c.participant},message:c.quotedMessage}:ctx.msg;let b;try{b=await downloadMediaMessage(target,'buffer',{}, {logger:console,reuploadRequest:ctx.sock.updateMediaMessage})}catch{}if(!b)throw new Error('Responde a una imagen.');const dir=path.resolve('data','group-media');await fs.mkdir(dir,{recursive:true});const file=path.join(dir,`${ctx.chat.replace(/[^a-z0-9]/gi,'_')}-${key}.jpg`);await fs.writeFile(file,b);patchGroup(ctx.chat,{[key==='welcome'?'welcomeImage':'goodbyeImage']:file});await ctx.sock.sendMessage(ctx.chat,{text:`✅ Imagen de ${key==='welcome'?'bienvenida':'despedida'} guardada.`},{quoted:ctx.msg})}
export const setwelcomeimage=wrap('setimgbienvenida',[],ctx=>saveGroupImage(ctx,'welcome'))
export const setgoodbyeimage=wrap('setimgdespedida',[],ctx=>saveGroupImage(ctx,'goodbye'))
export const setname=wrap('setname',['nombregrupo'],async ctx=>{await requireBotAdmin(ctx);const name=ctx.args.join(' ').trim();if(!name)throw new Error('Uso: .setname <nombre>');await ctx.sock.groupUpdateSubject(ctx.chat,name);await ctx.sock.sendMessage(ctx.chat,{text:'✅ Nombre del grupo actualizado.'},{quoted:ctx.msg})})
export const setdesc=wrap('setdesc',['descgrupo'],async ctx=>{await requireBotAdmin(ctx);const desc=ctx.args.join(' ').trim();if(!desc)throw new Error('Uso: .setdesc <descripción>');await ctx.sock.groupUpdateDescription(ctx.chat,desc);await ctx.sock.sendMessage(ctx.chat,{text:'✅ Descripción actualizada.'},{quoted:ctx.msg})})
export const open=wrap('abrir',['open'],async ctx=>{await requireBotAdmin(ctx);await ctx.sock.groupSettingUpdate(ctx.chat,'not_announcement');await ctx.sock.sendMessage(ctx.chat,{text:'🔓 Grupo abierto.'},{quoted:ctx.msg})})
export const close=wrap('cerrar',['close'],async ctx=>{await requireBotAdmin(ctx);await ctx.sock.groupSettingUpdate(ctx.chat,'announcement');await ctx.sock.sendMessage(ctx.chat,{text:'🔒 Grupo cerrado.'},{quoted:ctx.msg})})
export const opentimer=wrap('abrirgrupo',[],ctx=>scheduleGroup(ctx,'not_announcement'))
export const closetimer=wrap('cerrargrupo',[],ctx=>scheduleGroup(ctx,'announcement'))
export const promote=wrap('promote',['daradmin'],async ctx=>{await requireBotAdmin(ctx);const t=targetFromMsg(ctx);if(!t)throw new Error('Menciona o responde al usuario.');await ctx.sock.groupParticipantsUpdate(ctx.chat,[t],'promote')})
export const demote=wrap('demote',['quitaradmin'],async ctx=>{await requireBotAdmin(ctx);const t=targetFromMsg(ctx);if(!t)throw new Error('Menciona o responde al usuario.');await ctx.sock.groupParticipantsUpdate(ctx.chat,[t],'demote')})
export const kick=wrap('kick',['expulsar'],async ctx=>{await requireBotAdmin(ctx);const t=targetFromMsg(ctx);if(!t)throw new Error('Menciona o responde al usuario.');await ctx.sock.groupParticipantsUpdate(ctx.chat,[t],'remove')})
export const warn=wrap('warn',['advertir'],async ctx=>{await requireBotAdmin(ctx);const t=targetFromMsg(ctx);if(!t)throw new Error('Menciona o responde al usuario.');const count=setWarn(ctx.chat,t,getWarn(ctx.chat,t)+1);const reason=ctx.args.filter(x=>!x.startsWith('@')).join(' ')||'Sin motivo';if(count>=3){await ctx.sock.sendMessage(ctx.chat,{text:`🚫 @${t.split('@')[0]} llegó a 3 advertencias y será expulsado.\nMotivo: ${reason}`,mentions:[t]});await ctx.sock.groupParticipantsUpdate(ctx.chat,[t],'remove');resetWarn(ctx.chat,t)}else await ctx.sock.sendMessage(ctx.chat,{text:`⚠️ @${t.split('@')[0]} recibió una advertencia (${count}/3).\nMotivo: ${reason}`,mentions:[t]},{quoted:ctx.msg})})
export const warns=wrap('warns',[],async ctx=>{await requireAdmin(ctx);const t=targetFromMsg(ctx);if(!t)throw new Error('Menciona o responde al usuario.');await ctx.sock.sendMessage(ctx.chat,{text:`⚠️ @${t.split('@')[0]} tiene ${getWarn(ctx.chat,t)}/3 advertencias.`,mentions:[t]},{quoted:ctx.msg})})
export const resetwarn=wrap('resetwarn',['unwarn'],async ctx=>{await requireAdmin(ctx);const t=targetFromMsg(ctx);if(!t)throw new Error('Menciona o responde al usuario.');resetWarn(ctx.chat,t);await ctx.sock.sendMessage(ctx.chat,{text:`✅ Advertencias reiniciadas para @${t.split('@')[0]}.`,mentions:[t]},{quoted:ctx.msg})})
export const groupconfig=wrap('groupconfig',['configgrupo'],async ctx=>{await requireAdmin(ctx);const g=getGroup(ctx.chat);await ctx.sock.sendMessage(ctx.chat,{text:`⚙️ *Configuración del grupo*\nAnti-NSFW: ${g.antiNsfw?'ON':'OFF'}\nAnti-enlaces: ${g.antiLink?'ON':'OFF'}\nBienvenida: ${g.welcome?'ON':'OFF'}\nDespedida: ${g.goodbye?'ON':'OFF'}`},{quoted:ctx.msg})})
export const tagall=wrap('tagall',[],async ctx=>{const m=await requireAdmin(ctx);const ids=m.participants.map(x=>x.id);await ctx.sock.sendMessage(ctx.chat,{text:`📢 ${ctx.args.join(' ')||'Atención a todos'}\n\n${ids.map(x=>`@${x.split('@')[0]}`).join(' ')}`,mentions:ids},{quoted:ctx.msg})})
export const hidetag=wrap('hidetag',[],async ctx=>{const m=await requireAdmin(ctx);await ctx.sock.sendMessage(ctx.chat,{text:ctx.args.join(' ')||'📢 Atención',mentions:m.participants.map(x=>x.id)},{quoted:ctx.msg})})
export const moderationCommands=[antinsfw,antilink,welcome,goodbye,setwelcome,setgoodbye,setwelcomeimage,setgoodbyeimage,setname,setdesc,open,close,opentimer,closetimer,promote,demote,kick,warn,warns,resetwarn,groupconfig,tagall,hidetag]
