import fs from 'node:fs/promises'
import path from 'node:path'
import config from '../../config.js'

const reactions = [{"name": "hug", "aliases": ["abrazo", "abrazar"], "label": "Abrazar a alguien", "action": "abrazó a", "target": true}, {"name": "kiss", "aliases": ["beso", "besar"], "label": "Besar a alguien", "action": "besó a", "target": true}, {"name": "pat", "aliases": ["acariciar", "palmadita"], "label": "Acariciar a alguien", "action": "acarició a", "target": true}, {"name": "slap", "aliases": ["bofetada", "cachetada"], "label": "Dar una bofetada", "action": "le dio una bofetada a", "target": true}, {"name": "punch", "aliases": ["golpear", "puñetazo"], "label": "Dar un puñetazo", "action": "golpeó a", "target": true}, {"name": "kick", "aliases": ["patear", "patada", "patea", "pateae"], "label": "Dar una patada", "action": "pateó a", "target": true}, {"name": "bite", "aliases": ["morder"], "label": "Morder a alguien", "action": "mordió a", "target": true}, {"name": "bonk", "aliases": ["mazazo"], "label": "Dar un bonk", "action": "le dio un bonk a", "target": true}, {"name": "bully", "aliases": ["molestar"], "label": "Molestar a alguien", "action": "molestó a", "target": true}, {"name": "highfive", "aliases": ["chocalas", "chocar"], "label": "Chocar los cinco", "action": "chocó los cinco con", "target": true}, {"name": "handhold", "aliases": ["tomarmano"], "label": "Tomar de la mano", "action": "tomó de la mano a", "target": true}, {"name": "cuddle", "aliases": ["acurrucar"], "label": "Acurrucarse con alguien", "action": "se acurrucó con", "target": true}, {"name": "wave", "aliases": ["saludar"], "label": "Saludar a alguien", "action": "saludó a", "target": true}, {"name": "kill", "aliases": ["matar"], "label": "Derrotar de forma ficticia", "action": "derrotó de forma ficticia a", "target": true}, {"name": "cry", "aliases": ["llorar", "llora"], "label": "Llorar", "action": "está llorando", "target": false}, {"name": "laugh", "aliases": ["reir", "risa"], "label": "Reír", "action": "se está riendo", "target": false}, {"name": "blush", "aliases": ["sonrojar"], "label": "Sonrojarse", "action": "se sonrojó", "target": false}, {"name": "shy", "aliases": ["timido", "timida"], "label": "Sentir timidez", "action": "siente mucha timidez", "target": false}, {"name": "sleep", "aliases": ["dormir", "duerme"], "label": "Dormir", "action": "se quedó dormido/a", "target": false}, {"name": "dance", "aliases": ["bailar", "baila"], "label": "Bailar", "action": "está bailando", "target": false}, {"name": "smile", "aliases": ["sonreir", "sonrie"], "label": "Sonreír", "action": "está sonriendo", "target": false}, {"name": "happy", "aliases": ["feliz"], "label": "Estar feliz", "action": "está muy feliz", "target": false}, {"name": "sad", "aliases": ["triste"], "label": "Estar triste", "action": "está triste", "target": false}, {"name": "angry", "aliases": ["enojado", "enojada"], "label": "Enojarse", "action": "está muy enojado/a", "target": false}]

function contextInfo(msg){const m=msg?.message||{};return m.extendedTextMessage?.contextInfo||m.imageMessage?.contextInfo||m.videoMessage?.contextInfo||m.documentMessage?.contextInfo||{}}
function mentionName(jid=''){return `@${String(jid).split('@')[0].split(':')[0]}`}
function typedTarget(args=[]){const m=args.join(' ').match(/@(\d{7,20})/);return m?`${m[1]}@s.whatsapp.net`:''}
function makeReaction(def){return {name:def.name,aliases:def.aliases,description:def.label,async execute(ctx){const ci=contextInfo(ctx.msg);const target=ci?.mentionedJid?.[0]||ci?.participant||typedTarget(ctx.args);if(def.target&&!target){await ctx.sock.sendMessage(ctx.chat,{text:`❌ Debes mencionar a una persona o responder a su mensaje.\n\nEjemplo: *${config.prefix}${def.name} @usuario*`},{quoted:ctx.msg});return}const mediaPath=path.resolve('assets','reactions',`${def.name}.mp4`);const video=await fs.readFile(mediaPath);const actor=mentionName(ctx.sender);const caption=def.target?`🎭 *${actor} ${def.action} ${mentionName(target)}.*\n> ✐ ${def.label}.`:`🎭 *${actor} ${def.action}.*\n> ✐ ${def.label}.`;await ctx.sock.sendMessage(ctx.chat,{video,gifPlayback:true,caption,mentions:def.target?[ctx.sender,target]:[ctx.sender]},{quoted:ctx.msg})}}}
export const reactionsMenu={name:'reacciones',aliases:['reactions','acciones'],description:'Muestra todas las reacciones disponibles.',async execute(ctx){const body=['✦════ < 🎭 REACCIONES > ════⚝','',...reactions.flatMap(r=>[`✦ *${config.prefix}${r.name}${r.target?' @usuario':''}*`,`> ✐ ${r.label}.`,''])].join('\n');await ctx.sock.sendMessage(ctx.chat,{text:body},{quoted:ctx.msg})}}
export const reactionCommands=[reactionsMenu,...reactions.map(makeReaction)]
